apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: core.halo.run
    kind: LinkGroup
  formSchema:
    - $formkit: text
      name: "icon"
      label: "图标"
      help: "图标名称，支持所有 iconify 图标。例如 https://icones.netlify.app/"
